apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: dockerproject_api
          ports:
            - containerPort: 5432
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: simple_blog_api
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: postgres_password